apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pega
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pega
    spec:
      containers:
        - name:  pega
          image: pegaregistry.azurecr.io/postgres:pega:0.1
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
